name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8364666c706b1ac6d96e38973f80bbb3373efaf8316880a0b10b3dd9c38d30e0"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
