name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "457c9dafc63e5d4a2ae03be7b542a6f8844d751a11dbbac5a467a94e62baf5d6"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
