name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b03c69eeeafe92f443a0be161373ace557996f98282c537a4aebed5e08b8f0f6"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
