name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91b0cd59265db540ee2d170906909cf6f43255c20ca310ab82f1495043b7949a"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
