name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c957b8a01174c9ca983a168aef1a802e390dd183070a4ccdc4aa1d6e3c5724d7"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
