name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47043a476dbfb429c2e0ff489b57486086a091a9e3ca4aea5c701980c19b2971"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
