name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1344c9549978c1bcd1b403d30b6ade161d79a159ef1246fa721a83ad6eea249"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
