name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf39db9aa7e45c35807044b6cb7c6bbdf0fe0ecfa7402d9d19986e8c502826bf"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
