name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c5b1882a2aa20864cc03c9ddb3ed654d849636d2da023533f307d0642bb2711"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
