name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f28b2aaef341a9a3929064f63a9783eb6cfb5eae7f27c00029495c3ca76aa4ff"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
