name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87d91a4c4f1a832f06d1d3995d10a7c0c7b068b4f63ad9a1718c792cfa61b7fc"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
