name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24e198806ab99ae64a4f3be1cdcdaaf41ea99e6ed32e808a2f978cb9479b5fed"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
