name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7d9fdecec6fadf4e0018b7fe99b7433061bc72510c9664c5d5098086190c59d"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
