name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6681d51a92a06e35df548be8e265806b4e9b966297790b8d026dae638405d6df"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
