name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6887f9da15d6a74a66e2a8a5a90c25c0a98dcbec5afe213c0cc566fa6e50b122"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
