name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3c0372cb665477d3b7051d94c7c6d1c9c30f7f8c7ae5f3346d98799e9f30e91"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
