name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52b99d67629d256470030b6289ad1fc0dd2f1708d5333378385836ce8a4bec47"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
