name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c83937adb1e85c74c9a53233ab84dfca53784917ad1d62c1ca8e1c2757dd2209"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
