name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddd2c9cb70a7f6a3e6c7e1a2c431881026c8f5e41150b67aa350e41379443e00"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
