name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0529734b7c06a17f3c6d9c4cc3acf3ae17c9bebe5bd0279e09e377f610577943"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
