name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "473d608a35b5da3e383973029259d9917e7b49c6d43ed34cfc8a7a9267466b35"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
