name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beb9dc2f6bb7dfaaf208770c60dcd0cadfecce1fea89464579b11371b0397fb4"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
