name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67c20403c9de4fc87603f1259aabcd8d0defb702fba5c1c507e1c3b6829f0100"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
