name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051a2f16632a00b66d3b34221b5eae089bf4751ab7dd01231c786b428e297ef5"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
