name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1a557f335592f9d69ead30f1452d8916b15e14c02c5fd87955d7498b182b2ca"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
