name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe519574dc4de075e6f509c7c974eb46a8e5eb954a3448c9e5b5afe7dd21b5b3"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
