name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85d5a4e17f5b88f278181de52d7e9f1229c527a72bafd056f481241835d4234a"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
