name = "TFC Voltworks"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2d49aa8f7b536cfe0cccb3f773eaabcc71b6fec19755212f6203c55b2ebe34"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
