
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_ednabld = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.tfc]
				acacia = true
				ash = true
				aspen = true
				birch = true
				blackwood = true
				chestnut = true
				douglas_fir = true
				hickory = true
				kapok = true
				mangrove = true
				maple = true
				oak = true
				palm = true
				pine = true
				rosewood = true
				sequoia = true
				spruce = true
				sycamore = true
				white_cedar = true
				willow = true

	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.create]
				window_pane = true
				window = true

